config/routes.rb
Aesg::Application.routes.draw do
  get "schedule_approve/index"
  put "schedule_approve/approve/:id"  => 'schedule_approve#approve'
  put "schedule_approve/reprove/:id"  => 'schedule_approve#reprove'
  
  resources :addresses

  get "schedule_remove/remove"
  get "customer_addresses/create/:id_customer" => 'customer_addresses#create'
  get "customer_addresses/update/:id_customer/address/:id" => 'customer_addresses#edit'

  resources :schedules
  
  resources :customers do
    resources :cnhs #, only: [:index, :create, :update]
  end
  
  resources :customer_phones, only: [:create, :update, :destroy]

  resources :instructors

  resources :vehicles

  root 'home#index'

end

app/models/schedule.rb
class ScheduleValidator < ActiveModel::Validator
  def validate(record)
    unless record.times.include? record.time.strftime("%H:%M")
      record.errors[:event] << 'Horário inválido.'
    end
  end
end

class VehicleValidator < ActiveModel::Validator
  def validate(record)
    return if record.id.present? || record.errors.any?
      
    if record.findVehicleAndFilterByTime(record.date, record.vehicle_id, record.time).present?
      record.errors[:event] << 'Já existe um veículo cadastrado para a data e hora selecionadas.'
    end
  end
end

class CustomerValidator < ActiveModel::Validator
  def validate(record)
    return if record.id.present? || record.errors.any?
    
    schedules = Schedule.where('date = ? and customer_id = ?', record.date, record.customer_id)
    
    if schedules.size >= Schedule::Max_classes_day
      record.errors[:event] << 'Limite de aulas atigindas para este aluno.'
    elsif schedules.any?{|s| s.time == record.time}
      record.errors[:event] << 'Já existe um aluno cadastrado para a data e hora selecionadas.'
    end
  end
end

class Schedule < ActiveRecord::Base
  Week_interval = 6
  Max_classes_day = 3
  
  attr_accessor :date_init, :date_end
  
  validates_presence_of :event, :date, :time, :vehicle_id, :instructor_id, :customer_id
  validates_with ScheduleValidator, VehicleValidator, CustomerValidator
  
  def times
    ['07:10', '08:00', '08:50', '09:40', '10:30', '11:20', '12:10', '13:00', '13:50', '14:40', '15:30', '16:20', '17:10', '18:00', '18:50', '19:40', '20:30', '21:20']
  end
  
  def findVehicleAndFilterByTime(date, vehicle_id, time)
    schedules = Schedule.where('date = ? and vehicle_id = ?', date, vehicle_id)
    schedules.each do |s|
      #return s if s.time.strftime("%H:%M") == time
      return s if s.time == time
    end
    return nil
  end

  #def week_interval 5 end
 
  #@schedule.date_init.strftime("%d/%m/%Y")
  belongs_to :vehicle
  belongs_to :instructor
  belongs_to :customer
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedule = Schedule.new
    
    if params[:date_init].nil?
      @schedule.date_init = Date.today 
    else
      @schedule.date_init = DateTime.parse(params[:date_init], "%d/%m/%Y").to_date
    end
    
    @schedule.date_end = @schedule.date_init + Schedule::Week_interval
    
    #@schedules = Schedule.where(date: @schedule.date_init..@schedule.date_end).includes("customer").order("customers.name")
    @schedules = Schedule.where(date: @schedule.date_init..@schedule.date_end).includes("vehicle").order("vehicles.show_order")
    
    @vehicles = Vehicle.by_order.where("active = ?", true)
    @customers = Customer.all
    @instructors = Instructor.where("active = ?", true)
    
  end
  
  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @schedule }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:event, :date, :time, :vehicle_id, :instructor_id, :customer_id, :date_init)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.text_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :instructor_id %><br>
    <%= f.text_field :instructor_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
	<style>
		.lnk_add{
			margin-left: 30px;
		}
		.btn_add{
			width: 15px;
		}
	</style>
	<script>
		$(document).ready(function(){
			$('.fnc_add').click(function(){
				var tipo = $('#evento').val();
				var evento;
				
				var v = $('#veiculo :selected').text();
				var a = $('#aluno :selected').text();
				var cnt = $(this).parents('.panel')
						.find('.panel-body');				

				if(tipo == 0){//aula
					var i = $('#instrutor :selected').text();
					evento = '<p><small>' + v + ' - ' + a + ' - <br />INSTRUTOR: ' + i + '</small></p> <hr />';
				}else if(tipo == 1){//exame
					evento = '<p><small>' + v + ' - EXAME</small></p> <hr />';
				}else if(tipo == 2){//intervalo
					evento = '<p><small>' + v + ' - INTERVALO</small></p> <hr />';
				}else if(tipo == 3){//outro
					var d = $('#evento_desc').val();
					evento = '<p><small>' + v + ' - ' + d + '</small></p> <hr />';
				}
				
				
				$("#schedule_event").val(evento);
				$("#schedule_date").val($(this).attr("data-date"));
				$("#schedule_time").val($(this).attr("data-time"));
				$("#schedule_vehicle_id").val($('#veiculo :selected').val());
				$("#schedule_instructor_id").val($('#instrutor :selected').val());
				$("#schedule_customer_id").val($('#aluno :selected').val());
				
				$.ajax({
					type: "POST",
					dataType: "JSON",
					url: $(".new_schedule").attr("action"),
					data: $(".new_schedule").serialize()
					
				}).done(function() {
					id_field =  $("#schedule_date").val() + "-" + $("#schedule_time").val().replace(":", "_") + "-" + $("#schedule_vehicle_id").val();
					id_control_customer = $("#schedule_date").val() + "-c-" + $("#schedule_customer_id").val();
					
					temp = $("<span />").attr("id", id_field);
					temp.append(evento).append($("<span />").addClass(id_control_customer));
					cnt.append(temp);
					
					verifyButtons();
					
				}).error(function(x, textStatus, errorThrown){
					alert( "Erro ao agendar: " + x.responseJSON.event);
				});
				
			});
			
			$('.fnc_rem').click(function(){
				
				if(!confirm("Remover agendamento?")){
					return;
				}
				
				var v = $('#veiculo :selected').text();
				
				$("#_date").val($(this).attr("data-date"));
				$("#_time").val($(this).attr("data-time"));
				$("#_vehicle_id").val($('#veiculo :selected').val());
				
				$.ajax({
					type: "GET",
					dataType: "JSON",
					url: $("#destroy_schedule").attr("action"),
					data: $("#destroy_schedule").serialize()
					
				}).done(function(){
					id_field =  $("#_date").val() + "-" + $("#_time").val().replace(":", "_") + "-" + $("#_vehicle_id").val();
					$('#' + id_field).remove();
					resetButtons();
					verifyButtons();
					
				}).fail(function(){
					alert( "Erro ao remover agendamento." );
				});
				
			});
			
			//reload
			function reload(){
				<% @schedules.each do |s| %>
					<% 
						id_field =  s.date.to_s + "-" + s.time.strftime("%H_%M")
						id_control =  id_field + "-" + s.vehicle_id.to_s #+ s.customer_id.to_s
						id_control_customer = s.date.to_s + "-c-" + s.customer_id.to_s
					%>
					temp = $('<span id="<%= id_control %>" />')
						.append('<span class="<%= id_control_customer %>" />')
						.append("<%= s.event.html_safe %>");
					$('#<%= id_field %>').append(temp);
				<% end %>
			}
			
			function changeButton(){
			
				$(".blc_crl").each(function(){
					id_field = $(this).attr("id");
					id_control = id_field + "-" + $('#veiculo :selected').val();// + $('#aluno :selected').val();
					
					if($("#" + id_control).length){
						lnk = $("#" + id_control).parent().parent();
						lnk.find(".lnk_add").hide();
						lnk.find(".lnk_rem").show();
					}

				});
			}
			
			function changeButtonCustomer(){
				$(".lnk_ok").hide();
				
				$(".h_crl").each(function(){
					id_field = $(this).attr("id");
					id_control = id_field + "-c-" + $('#aluno :selected').val();
				
					if($("." + id_control).length >= <%= Schedule::Max_classes_day %>){
						$(".h_add_" + id_field).hide();
						$(".h_ok_" + id_field).show();
						
					} else if($("." + id_control).length != 0){
						p = $("." + id_control).parent().parent().parent(); 
						p.find(".h_add_" + id_field).hide();
						p.find(".h_ok_" + id_field).show();
					}

				});
			}			
			
			function resetButtons(){
				$(".lnk_add").show();
				$(".lnk_rem").hide();
				$(".lnk_ok").hide();
			}
			
			function verifyButtons(){
				changeButton();
				changeButtonCustomer();
			}
			
			$('#evento').change(function(){
				if($('#evento').val() == 3){
					$('#evento_desc').show();
				}else{
					$('#evento_desc').hide();
				}
			});
			
			$( "#sel_date_ini" ).datepicker({
				//$.datepicker.regional[ "br" ]
				dateFormat: "dd/mm/yy"
				
			}).change(function(){
				$('#filter_schedule').submit();
			});
			
			$('#veiculo').change(function(){
				$('#instrutor').val($('#veiculo :selected').attr('data-instructor'));
				resetButtons();
				verifyButtons();
			});
			
			$('#aluno').change(function(){
				resetButtons();
				verifyButtons();
			});	

			reload();			
			verifyButtons();
		});
	</script>
	<%= form_for @schedule do |f| %>
		<%= f.hidden_field :event %>
		<%= f.hidden_field :date %>
		<%= f.hidden_field :time %>
		<%= f.hidden_field :vehicle_id %>
		<%= f.hidden_field :instructor_id %>
		<%= f.hidden_field :customer_id %>
	<% end %>
	
	<%= form_tag schedule_remove_remove_path, :html => {:method => 'delete', :remote => true}, :id => 'destroy_schedule' do |f| %>
		<%= hidden_field_tag :date, 0, :id => "_date"  %>
		<%= hidden_field_tag :time, 0, :id => "_time" %>
		<%= hidden_field_tag :vehicle_id, 0, :id => "_vehicle_id" %>
	<% end %>	
	
	<!-- <div class="page-header">
		<h1>Agendamento</h1>
	</div> -->
	<div class="_container">
	<div class="form-horizontal">
		
	<%= form_tag schedules_path, :method => 'get', :id => 'filter_schedule' do |f|
	#= form_tag rooms_path, method: :get, class: 'search' do 
	%>
		<p>
			<select id="veiculo" class="input-xlarge upper">
			<% @vehicles.each do |vehicle| %>
				<option value="<%= vehicle.id %>" 
					data-instructor="<%= vehicle.instructor.id if vehicle.instructor.present? %>"><%= vehicle.name %></option>
			<% end %>
			</select>
			
			<select id="aluno" class="upper">
			<% @customers.each do |custumer| %>
				<option value="<%= custumer.id %>"><%= custumer.name %></option>
			<% end %>
			</select>		
			<span>Mostrar semana:</span>
			<%= text_field_tag :date_init, I18n.l(@schedule.date_init), :id => 'sel_date_ini', :class => 'input-small'  %>
		</p>
		<p>Instrutor padrão: <span id="insp"></span> 		
			<select id="instrutor" class="upper">
				<% @instructors.each do |instructor| %>
				<option value="<%= instructor.id %>"><%= instructor.name %></option>
				<% end %>
			</select>	
			 | <span> Evento</span>
			<select id="evento" class="upper">
				<option value="0">Aula</option>
				<option value="1">Exame</option>
				<option value="2">Intervalo</option>
				<option value="3">Outro</option>
			</select>
			<input id="evento_desc" type="text" value="" style="display:none;" />			
		</p>
	<% end %>
			
		<!-- <h2>Horários</h2> -->
		<hr />
		<div>
			<div class="row">		
<%
	col = 0
	(@schedule.date_init..@schedule.date_end).map{ |d|
		next if d.sunday?
%>
				<div id="<%= d.to_s %>" class="col-sm-2 h_crl" style='<%= "background-color: darkkhaki;" if d.sunday? %>'><%= I18n.l d, :format => :short_custom %>
<%
		@schedule.times.each{ |t| 
%>					
					<div class="panel <%= col.even? ? 'panel-default' : 'panel-info' %>">
						<div class="panel-heading">
							<h3 class="panel-title">
								<span class="hora"><%= t %></span>
								
								<span class=""><a href="javascript:void()" title="Adicionar à <%= I18n.l d, :format => :short %>" class="fnc_add h_add_<%= d.to_s %> lnk_add" data-date="<%= d %>" data-time="<%= t %>">
									<img class="btn_add" src="assets/add.png" /></a></span>
									
								<span class="lnk_rem" style="display:none;"><a href="javascript:void()" title="Remover de <%= I18n.l d, :format => :short %>" class="fnc_rem" data-date="<%= d %>" data-time="<%= t %>">
									<img class="btn_add" src="assets/rem.png" /></a></span>
									
								<span class="lnk_ok h_ok_<%= d.to_s %>" style="display:none;">
									<img class="btn_add" src="assets/ok.png" title="Aluno adicionado ou número máximo de aulas diárias atingidos." /></a></span>																		
							</h3>
						</div>
						<div id="<%= d %>-<%= t.gsub(/:/, '_') %>" class="blc_crl panel-body">
							<!-- content -->
						</div>
					</div>
<%
		}
%>
				</div>
<%
		col = col + 1
	}
%>
			</div>
		</div>
	</div>
	</div>

app/views/schedules/list.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Date</th>
      <th>Time</th>
      <th>Vehicles</th>
      <th>Instructor</th>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.event %></td>
        <td><%= schedule.date %></td>
        <td><%= schedule.time %></td>
        <td><%= schedule.vehicle %></td>
        <td><%= schedule.instructor %></td>
        <td><%= schedule.customer %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @schedule.event %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @schedule.time %>
</p>

<p>
  <strong>Vehicles:</strong>
  <%= @schedule.vehicle %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @schedule.instructor %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @schedule.customer %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>