config/routes.rb
Aesg::Application.routes.draw do
  get "schedule_approve/index"
  put "schedule_approve/approve/:id"  => 'schedule_approve#approve'
  put "schedule_approve/reprove/:id"  => 'schedule_approve#reprove'
  
  resources :addresses

  get "schedule_remove/remove"
  get "customer_addresses/create/:id_customer" => 'customer_addresses#create'
  get "customer_addresses/update/:id_customer/address/:id" => 'customer_addresses#edit'

  resources :schedules
  
  resources :customers do
    resources :cnhs #, only: [:index, :create, :update]
  end
  
  resources :customer_phones, only: [:create, :update, :destroy]

  resources :instructors

  resources :vehicles

  root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  validates_presence_of :name
  
  has_many :cnhs, dependent: :destroy
  
  has_many :customer_addresses, dependent: :destroy
  has_many :addresses, through: :customer_addresses, source: :address
  
  has_many :customer_phones, dependent: :destroy
  has_many :phones, through: :customer_phones, source: :phone 
  
  
  #accepts_nested_attributes_for :customer_addresses, :allow_destroy => true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @address = Address.new
    @address_business = Address.new
    
    @phoneRes = Phone.new
    @phoneCel = Phone.new
    @phoneRec = Phone.new
    @phoneRecCel = Phone.new
    @phoneCom = Phone.new    
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.json { render action: 'show', status: :created, location: @customer }#format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
      @address = @customer.addresses.first || Address.new
      @address_business = @customer.addresses.second || Address.new
      @phones = @customer.phones
      
      @phoneRes = @phones[0] || Phone.new
      @phoneCel = @phones[1] || Phone.new
      @phoneRec = @phones[2] || Phone.new
      @phoneRecCel = @phones[3] || Phone.new
      @phoneCom = @phones[4] || Phone.new
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :fname, :mname, :country, :city, :uf, :birth, :email, :annotation, :schooling, :civil_status, :cpf, :rg)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<style>
	.row {
		margin-top: 20px;
	}
</style>
<script>
	$(document).ready(function() {
		$("#customer_cpf").mask("999.999.999.99");
		$("#customer_rg").mask("99.999.999-*");
		$("#customer_uf").mask("aa");

		$("#address_zip_code").mask("99999-999");

		$('#myTab a').click(function(e) {
			e.preventDefault()
			$(this).tab('show')
		});

		$('#btn_save').click(function() {
			var id = null;
			//save customer
			$.ajax({
				type : "POST",
				dataType : "JSON",
				async : false,
				url : $('#new_customer').attr("action"),
				data : $('#new_customer').serialize()
			}).done(function(data) {
				id = data.id;
			}).fail(function(data) {
				alert("Erro: Campos não preenchidos corretamente.");
			});

			if (id != null) {
				var success = true;
				//save address
				url = $("#address_id").val() == '' ? '/customer_addresses/create/' + id : '/customer_addresses/update/' + id + '/address/' + $("#address_id").val();
				$.ajax({
					type : "GET",
					dataType : "JSON",
					async : false,
					url : url,
					data : $('#edit_address').serialize()
				}).done(function(data) {
				}).fail(function() {
					success = false;
					alert("Erro ao salvar endereço.");
				});

				//save business address
				url = $("#business_address_id").val() == '' ? '/customer_addresses/create/' + id : '/customer_addresses/update/' + id + '/address/' + $("#business_address_id").val();
				$.ajax({
					type : "GET",
					dataType : "JSON",
					async : false,
					url : url,
					data : $('#edit_business_address').serialize()
				}).done(function(data) {
				}).fail(function() {
					success = false;					
					alert("Erro ao salvar endereço comercial.");
				});

				//save phone

				$("#edit_phone_res #customer_id").val(id);
				if(!savePhones($("#edit_phone_res"))){
					success = false;
					alert("Erro ao salvar telefones.");	
				}
				
				$("#edit_phone_cel #customer_id").val(id);
				if(!savePhones($("#edit_phone_cel"))){
					success = false;
					alert("Erro ao salvar telefones.");	
				}
								
				$("#edit_phone_rec_tel #customer_id").val(id);
				if(!savePhones($("#edit_phone_rec_tel"))){
					success = false;
					alert("Erro ao salvar telefones.");	
				}	
				
				$("#edit_phone_rec_cel #customer_id").val(id);
				if(!savePhones($("#edit_phone_rec_cel"))){
					success = false;
					alert("Erro ao salvar telefones.");	
				}	
				
				$("#edit_phone_com_tel #customer_id").val(id);
				if(!savePhones($("#edit_phone_com_tel"))){
					success = false;
					alert("Erro ao salvar telefones.");	
				}
			}
			
			if(success){
				window.location.replace("/customers/" + id);
			}				

		});
		
		function savePhones(_form){
			var url = _form.attr('action');
			var _r = false;
			
			if(_form.find("#phone_number").val() == "" 
				&& _form.find("#phone_id").val() == ""){
					
				return true;
			}
			
			$.ajax({
				type : "POST",
				dataType : "JSON",
				async : false,
				url : url,
				data : _form.serialize()
			}).done(function(data) {
				_r = true;
			}).fail(function() {
			});
			
			return _r;
		}
	}); 
</script>
<ul id="myTab" class="nav nav-tabs">
	<li class="active">
		<a href="#tab_customer">Dados Aluno</a>
	</li>
	<li>
		<a href="#tab_address">Endereço</a>
	</li>
	<li>
		<a href="#tab_business_address">Endereço Comercial</a>
	</li>
	<li>
		<a href="#tab_cellphone">Telefones</a>
	</li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="tab_customer">
		<%= form_for(@customer, :html=>{id: 'new_customer'}) do |f| %>
		<% if @customer.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
			<ul>
				<% @customer.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<div class="row">
			<div class="col-md-6">
				<div class="field">
					<%= f.label :name %>
					<br>
					<%= f.text_field :name %>
				</div>
				<div class="field">
					<%= f.label :fname %>
					<br>
					<%= f.text_field :fname %>
				</div>
				<div class="field">
					<%= f.label :mname %>
					<br>
					<%= f.text_field :mname %>
				</div>
				<div class="field">
					<%= f.label :country %>
					<br>
					<%= f.text_field :country %>
				</div>
				<div class="field">
					<%= f.label :city %>
					<br>
					<%= f.text_field :city %>
				</div>
				<div class="field">
					<%= f.label :uf %>
					<br>
					<%= f.text_field :uf %>
				</div>
				<div class="field">
					<%= f.label :birth %>
					<br>
					<%= f.date_select(:birth, :start_year => Time.new.year - 80, :end_year => Time.new.year - 17) %>
				</div>
			</div>
			<div class="col-md-6">
				<div class="field">
					<%= f.label :email %>
					<br>
					<%= f.text_field :email %>
				</div>
				<div class="field">
					<%= f.label :schooling %>
					<br>
					<%= f.text_field :schooling %>
				</div>
				<div class="field">
					<%= f.label :civil_status %>
					<br>
					<%= f.text_field :civil_status %>
				</div>
				<div class="field">
					<%= f.label :cpf %>
					<br>
					<%= f.text_field :cpf %>
				</div>
				<div class="field">
					<%= f.label :rg %>
					<br>
					<%= f.text_field :rg %>
				</div>
				<div class="field">
					<%= f.label :annotation %>
					<br>
					<%= f.text_area :annotation %>
				</div>
			</div>
		</div>
		<% end %>
	</div><!-- // tab_customer -->
	<div class="tab-pane" id="tab_address">

		<div class="row">
			<%= form_for(@address, :html=>{id: 'edit_address'}) do |fa| %>
			<div class="col-md-6">
				<div class="field">
					<%= fa.label :zip_code %>
					<br>
					<%= fa.text_field :zip_code %>
				</div>
				<div class="field">
					<%= fa.label :type_address %>
					<br>
					<%= fa.select(:type_address, options_for_select(['Apartamento', 'Casa', 'Outro'])) %>
				</div>
				<div class="field">
					<%= fa.label :address %>
					<br>
					<%= fa.text_field :address %>
				</div>
				<div class="field">
					<%= fa.label :number %>
					<br>
					<%= fa.text_field :number %>
				</div>
				<div class="field">
					<%= fa.label :complement %>
					<br>
					<%= fa.text_field :complement %>
				</div>
			</div>
			<div class="col-md-6">
				<div class="field">
					<%= fa.label :neighborhood %>
					<br>
					<%= fa.text_field :neighborhood %>
				</div>
				<div class="field">
					<%= fa.label :city %>
					<br>
					<%= fa.text_field :city %>
				</div>
				<div class="field">
					<%= fa.label :state %>
					<br>
					<%= fa.text_field :state %>
				</div>
				<div class="field">
					<%= fa.label :note %>
					<br>
					<%= fa.text_area :note %>
				</div>
				<%= fa.hidden_field :id %>
				<%= hidden_field_tag :commercial, false %>
			</div>
			<% end %>
		</div>
	</div><!-- tab_business_address -->
	<div class="tab-pane" id="tab_business_address">

		<div class="row">
			<%= form_for(@address_business, :html=>{id: 'edit_business_address'}) do |fa| %>
			<div class="col-md-6">
				<div class="field">
					<%= fa.label :zip_code %>
					<br>
					<%= fa.text_field :zip_code %>
				</div>
				<div class="field">
					<%= fa.label :type_address %>
					<br>
					<%= fa.select(:type_address, options_for_select(['Apartamento', 'Comercial', 'Outro'])) %>
				</div>
				<div class="field">
					<%= fa.label :address %>
					<br>
					<%= fa.text_field :address %>
				</div>
				<div class="field">
					<%= fa.label :number %>
					<br>
					<%= fa.text_field :number %>
				</div>
				<div class="field">
					<%= fa.label :complement %>
					<br>
					<%= fa.text_field :complement %>
				</div>
			</div>
			<div class="col-md-6">
				<div class="field">
					<%= fa.label :neighborhood %>
					<br>
					<%= fa.text_field :neighborhood %>
				</div>
				<div class="field">
					<%= fa.label :city %>
					<br>
					<%= fa.text_field :city %>
				</div>
				<div class="field">
					<%= fa.label :state %>
					<br>
					<%= fa.text_field :state %>
				</div>
				<div class="field">
					<%= fa.label :note %>
					<br>
					<%= fa.text_area :note %>
				</div>
				<%= fa.hidden_field(:id, :id => 'business_address_id') %>
				<%= hidden_field_tag :commercial, true %>
			</div>
			<% end %>
		</div>
	</div><!-- tab_address -->
	<div class="tab-pane" id="tab_cellphone">
		<div class="row">
			<%= form_for([@customer, @phoneRes], :html=>{id: 'edit_phone_res'}) do |fa| %>
			<div class="">
				<div class="field">
					<div class="field">
						<%= fa.label I18n.t :phone_code %> <%= fa.text_field :code %>
						<%= I18n.t :tel_res %> <%= fa.text_field :number %>
						<%= fa.label I18n.t :phone_description %> <%= fa.text_field :description %>
					</div>
				</div>
			</div>
			<div class="col-md-6"></div>

			<%= hidden_field_tag :customer_id, @customer.id %>
			<%= fa.hidden_field :id %>
			<% end %>
		</div>
		<div class="row">
			<%= form_for([@customer, @phoneCel], :html=>{id: 'edit_phone_cel'}) do |fa| %>
			<div class="">
				<div class="field">
					<div class="field">
						<%= fa.label I18n.t :phone_code %> <%= fa.text_field :code %>
						<%= I18n.t :cel_res %> <%= fa.text_field :number %>
						<%= fa.label I18n.t :phone_description %> <%= fa.text_field :description %>
					</div>
				</div>
			</div>
			<div class="col-md-6"></div>

			<%= hidden_field_tag :customer_id, @customer.id %>
			<%= fa.hidden_field :id %>
			<% end %>
		</div>
		<div class="row">
			<%= form_for([@customer, @phoneRec], :html=>{id: 'edit_phone_rec_tel'}) do |fa| %>
			<div class="">
				<div class="field">
					<div class="field">
						<%= fa.label I18n.t :phone_code %> <%= fa.text_field :code %>
						<%= I18n.t :tel_rec %> <%= fa.text_field :number %>
						<%= fa.label I18n.t :phone_description %> <%= fa.text_field :description %>
					</div>
				</div>
			</div>
			<div class="col-md-6"></div>

			<%= hidden_field_tag :customer_id, @customer.id %>
			<%= fa.hidden_field :id %>
			<% end %>
		</div>
		<div class="row">
			<%= form_for([@customer, @phoneRecCel], :html=>{id: 'edit_phone_rec_cel'}) do |fa| %>
			<div class="">
				<div class="field">
					<div class="field">
						<%= fa.label I18n.t :phone_code %> <%= fa.text_field :code %>
						<%= I18n.t :cel_rec %> <%= fa.text_field :number %>
						<%= fa.label I18n.t :phone_description %> <%= fa.text_field :description %>
					</div>
				</div>
			</div>
			<div class="col-md-6"></div>

			<%= hidden_field_tag :customer_id, @customer.id %>
			<%= fa.hidden_field :id %>
			<% end %>
		</div>		
		<div class="row">
			<%= form_for([@customer, @phoneCom], :html=>{id: 'edit_phone_com_tel'}) do |fa| %>
			<div class="">
				<div class="field">
					<div class="field">
						<%= fa.label I18n.t :phone_code %> <%= fa.text_field :code %>
						<%= I18n.t :tel_com %> <%= fa.text_field :number %>
						<%= fa.label I18n.t :phone_description %> <%= fa.text_field :description %>
					</div>
				</div>
			</div>
			<div class="col-md-6"></div>

			<%= hidden_field_tag :customer_id, @customer.id %>
			<%= fa.hidden_field :id %>
			<% end %>
		</div>
	</div><!-- tab_tel -->
	<button id="btn_save">
		Salvar
	</button>
</div>

app/views/customers/edit.html.erb
<h1>Editando <%= I18n.t 'activerecord.models.customer' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('links.show'), @customer %> |
<%= link_to I18n.t('links.back'), customers_path %>

app/views/customers/index.html.erb
<h1>Listando <%= I18n.t 'customer.title' %></h1>
<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t 'activerecord.attributes.customer.name' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.fname' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.mname' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.country' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.city' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.uf' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.birth' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.email' %></th>
      <th><%= I18n.t 'activerecord.attributes.customer.annotation' %></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.fname %></td>
        <td><%= customer.mname %></td>
        <td><%= customer.country %></td>
        <td><%= customer.city %></td>
        <td><%= customer.uf %></td>
        <td><%= I18n.l customer.birth %></td>
        <td><%= customer.email %></td>
        <td><%= customer.annotation %></td>
        <td><%= link_to 'CNH', customer_cnhs_path(customer) %></td>
        <td><%= link_to I18n.t('links.show'), customer %></td>
        <td><%= link_to I18n.t('links.edit'), edit_customer_path(customer) %></td>
        <td><%= link_to I18n.t('links.destroy'), customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Aluno', new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo <%= I18n.t 'activerecord.models.customer' %></h1>

<%= render 'form' %>

<%= link_to I18n.t('links.back'), customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @customer.fname %>
</p>

<p>
  <strong>Mname:</strong>
  <%= @customer.mname %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @customer.uf %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @customer.birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Annotation:</strong>
  <%= @customer.annotation %>
</p>

<%= link_to I18n.t('links.edit'), edit_customer_path(@customer) %> |
<%= link_to I18n.t('links.back'), customers_path %>