config/routes.rb
Aesg::Application.routes.draw do
  get "schedule_approve/index"
  put "schedule_approve/approve/:id"  => 'schedule_approve#approve'
  put "schedule_approve/reprove/:id"  => 'schedule_approve#reprove'
  
  resources :addresses

  get "schedule_remove/remove"
  get "customer_addresses/create/:id_customer" => 'customer_addresses#create'
  get "customer_addresses/update/:id_customer/address/:id" => 'customer_addresses#edit'

  resources :schedules
  
  resources :customers do
    resources :cnhs #, only: [:index, :create, :update]
  end
  
  resources :customer_phones, only: [:create, :update, :destroy]

  resources :instructors

  resources :vehicles

  root 'home#index'

end

app/models/cnh.rb
class Cnh < ActiveRecord::Base
  
  validates_presence_of :category, :registration, :validity, :customer_id
  
  belongs_to :customer
  belongs_to :photo, dependent: :destroy
  
end

app/controllers/cnhs_controller.rb
class CnhsController < ApplicationController
  before_action :set_cnh, only: [:show, :edit, :update, :destroy]

  # GET /cnhs
  # GET /cnhs.json
  def index
    @customer = Customer.find(params[:customer_id])
    @cnhs = @customer.cnhs
  end

  # GET /cnhs/1
  # GET /cnhs/1.json
  def show
  end

  # GET /cnhs/new
  def new
    @customer = Customer.find(params[:customer_id])
    @cnh = @customer.cnhs.build
  end

  # GET /cnhs/1/edit
  def edit
  end

  # POST /cnhs
  # POST /cnhs.json
  def create
    @customer = Customer.find(params[:customer_id])
    @cnh = @customer.cnhs.build(cnh_params)
    @photo = Photo.new
    
    uploaded_io = params[:cnh][:file]
    if uploaded_io.present?
      unless File.directory?('public/uploads')
        FileUtils::mkdir_p 'public/uploads'
      end      
      
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
        @photo.path = uploaded_io.original_filename
        @cnh.photo = @photo
      end        
    end

    respond_to do |format|
      if @cnh.save
        format.html { redirect_to [@customer, @cnh], notice: 'Cnh was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cnh }
      else
        format.html { render action: 'new' }
        format.json { render json: @cnh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cnhs/1
  # PATCH/PUT /cnhs/1.json
  def update
    
    uploaded_io = params[:cnh][:file]
    if uploaded_io.present?
      
      unless File.directory?('public/uploads')
        FileUtils::mkdir_p 'public/uploads'
      end      
      
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      
        if @cnh.photo.present?
          @cnh.photo.destroy
        end
        
        @photo = Photo.new
        @photo.path = uploaded_io.original_filename
        @cnh.photo = @photo
      end        
    end    
    
    respond_to do |format|
      if @cnh.update(cnh_params)
        format.html { redirect_to [@customer, @cnh], notice: 'Cnh was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cnh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cnhs/1
  # DELETE /cnhs/1.json
  def destroy
    @cnh.destroy
    respond_to do |format|
      format.html { redirect_to customer_cnhs_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cnh
      @customer = Customer.find(params[:customer_id])
      @cnh = Cnh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cnh_params
      params.require(:cnh).permit(:category, :registration, :first, :validity, :customer_id, :first_registration)
    end
end

app/helpers/cnhs_helper.rb
module CnhsHelper
end

app/views/cnhs/_form.html.erb
<%= form_for [@customer, @cnh] do |f| %>
  <% if @cnh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cnh.errors.count, "error") %> prohibited this cnh from being saved:</h2>

      <ul>
      <% @cnh.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :customer_id %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :registration %><br>
    <%= f.text_field :registration %>
  </div>
  <div class="field">
    <%= f.label :first %><br>
    <%= f.check_box :first %>
  </div>
  <div class="field">
    <%= f.label :first_registration %><br>
    <%= f.date_select(:first_registration, :start_year => Time.new.year - 62, :end_year => Time.new.year - 17) %>
  </div>  
  <div class="field">
    <%= f.label :validity %><br>
    <%= f.date_select :validity %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
	<% if @cnh.photo.present? %>
		<img src='/uploads/<%= @cnh.photo.path %>' style='max-width: 135px; padding-bottom: 15px' />
	<% end %>    
    <%= f.file_field :file %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cnhs/edit.html.erb
<h1>Editando CNH</h1>

<%= render 'form' %>

<%= link_to I18n.t('links.show'), customer_cnh_path(@customer, @cnh) %> |
<%= link_to I18n.t('links.back'), customer_cnhs_path(@customer) %>

app/views/cnhs/index.html.erb
<h1>Listando CNH</h1>

<h2><%= @customer.name %></h2>
<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Category</th>
			<th>Registration</th>
			<th>Primeira habitação</th>
			<th>Validity</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @cnhs.each do |cnh| %>
		<tr>
			<td>
				<% if cnh.photo.present? %>
					<img src='/uploads/<%= cnh.photo.path %>' style='max-width: 75px' />
				<% end %>
			</td>
			<td><%= cnh.category %></td>
			<td><%= cnh.registration %></td>
			<td><%= "Sim / " if cnh.first %> <%= I18n.l(cnh.first_registration) if cnh.first_registration.present?  %></td>
			<td><%= I18n.l cnh.validity %></td>
			<td><%= link_to I18n.t('links.show'), customer_cnh_path(@customer, cnh) %></td>
			<td><%= link_to I18n.t('links.edit'), edit_customer_cnh_path(@customer, cnh) %></td>
			<td><%= link_to I18n.t('links.destroy'), customer_cnh_path(@customer, cnh), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>
<%= link_to I18n.t('links.back'), customers_path %>
<%= link_to 'Nova CNH', new_customer_cnh_path(@customer) %>

app/views/cnhs/new.html.erb
<h1>Nova CNH</h1>

<%= render 'form' %>

<%= link_to I18n.t('links.back'), customer_cnhs_path(@customer) %>

app/views/cnhs/show.html.erb
<p id="notice"><%= notice %></p>

<% if @cnh.photo.present? %>
	<img src="/uploads/<%= @cnh.photo.path %>" />
<% end %>	
<p>
  <strong>Customer:</strong>
  <%= @cnh.customer.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @cnh.category %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @cnh.registration %>
</p>

<p>
  <strong>First:</strong>
  <%= @cnh.first %>
</p>

<p>
  <strong>Validity:</strong>
  <%= @cnh.validity %>
</p>

<%= link_to I18n.t('links.edit'), edit_customer_cnh_path(@customer, @cnh) %> |
<%= link_to I18n.t('links.back'), customer_cnhs_path(@customer) %>